#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

touch default
printf %s "server {
       listen 80;
       listen [::]:80;

       root /var/www/school;
       index index.html;

       location /redirect_me {
            return 301 https://www.youtube.com;
       }
}" > default 

sudo mv default /etc/nginx/sites-available/
sudo service nginx restart
