#!/usr/bin/env bash
# configure
apt-get update
apt-get install -y nginx

rm -rf school
mkdir school
touch school/index.html
echo "Hello World!" > school/index.html

sudo rm -rf /var/www/school
sudo mv school /var/www/

mkdir /etc/nginx/html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
        listen 80;
        listen [::]:80;

        root /var/www/school;
        index index.html;

        location /redirect_me {
            return 301 https://youtube.com;
        }

        error_page 404 /404.html;
        location /404 {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
