#!/usr/bin/env bash
# provides the status of a file 'school'

if [ -f "school" ]
then
    echo "school file exists"
    if [ -s "school" ]
    then
        echo "school file not is empty"
    else
        echo "school file is empty"
    fi
    echo "school is a regular file"
    
else
    echo "school file does not exist"
fi